### PR TITLE
feat: Fullscreen Mode

### PR DESCRIPTION
**Pull request by sumeshir26**
Better implimentation of @not-nef's fullscreen

### CODE REVIEW

**Comment by im-coder-lg** [comment]
Screenshot please?

**Comment by sumeshir26** [comment]
Yes

**Review by not-nef — CHANGES_REQUESTED** [review]
No, it doesnt work, it has the exact issue i told you about.

**Comment by not-nef** [comment]
Weird, the video doesn’t upload. Just believe me that it doesnt work.

**Comment by sumeshir26** [comment]
You can always close the app Crome the taskbar…

**Comment by im-coder-lg** [comment]
I think it might be fine, I'll test this evening.

**Comment by not-nef** [comment]
> You can always close the app Crome the taskbar…

After switching to fullscreen, and back, i cant anymore.

**Comment by sumeshir26** [comment]
Well, we'll drop this then. But i will take out the maxsize. I treid that locallay and it works pretty well. Also, did you see that the ttk theme is now on PyPi? Ill take care of upgrading TimerX

**Comment by not-nef** [comment]
Ok

**Comment by im-coder-lg** [comment]
> Also, did you see that the ttk theme is now on PyPi?

Really? Does it work with a PyPI import?

**Comment by sumeshir26** [comment]
Yeah

**Pull request closed without merging**
