### PR TITLE
feat: Code Formatting via cron

### PR DESCRIPTION
**Pull request by not-nef**
@sumeshir26 Can you please verify this works this is my first time doing something like this thanks

### CODE REVIEW

**Comment by im-coder-lg** [comment]
Hey, I wanted to do this! I have a bunch of workflow apps to do this.

**Comment by not-nef** [comment]
Well i was faster xd

**Comment by not-nef** [comment]
But i didnt figure out how to manually trigger a workflow

**Comment by im-coder-lg** [comment]
> But i didnt figure out how to manually trigger a workflow

It has to be on the master branch.

**Comment by not-nef** [comment]
Ah ok

**Comment by not-nef** [comment]
So theres no way to test if this works?

**Comment by not-nef** [comment]
> 

Yeah

**Comment by im-coder-lg** [comment]
> So theres no way to test if this works?

I'll test this on my other Python apps ;)

**Comment by not-nef** [comment]
Cool!

**Comment by im-coder-lg** [comment]
Some more commits incoming!

**Comment by not-nef** [comment]
Btw, can we rename the org to something like Futura-Software?

**Comment by im-coder-lg** [comment]
Well, let's wait for @sumeshir26's response. Moreover, I'll be offline tomorrow yet again, so it will be a loooong time before I get back onto GitHub.

**Comment by not-nef** [comment]
Okay

**Comment by sumeshir26** [comment]
@not-nef I'm not reallay in liking with Futura-Software. Could we try something else?

**Comment by not-nef** [comment]
Yeah, do you have any other ideas?

**Comment by sumeshir26** [comment]
You know what, I'll rename the org to `Futura-Software` Can someone make a logo?

**Comment by sumeshir26** [comment]
Futura-Software isnt available 😆

**Comment by im-coder-lg** [comment]
Futura-Tech?

**Comment by not-nef** [comment]
> You know what, I'll rename the org to `Futura-Software` Can someone make a logo?

I can make a logo, but not at the moment

**Comment by im-coder-lg** [comment]
What kind of logo? Maybe I'll be able to draw something on a balnk sheet of paper. Make sure it's geometric, I'll make the lengths and spacings.

**Comment by sumeshir26** [comment]
I've got a idea - Ill make it tommorow on Google Drawings

**Comment by im-coder-lg** [comment]
@not-nef why do you hate Futura-Tech? Close to your title, except I changed software to tech. Also, what do you guys think of a game in the future? Kind of like Atari Breakout?

**Comment by im-coder-lg** [comment]
Also ,any ideas on a repo token for checks? Or maybe I'll add just Black.

**Comment by im-coder-lg** [comment]
As well as isort.

**Comment by im-coder-lg** [comment]
Alright, I think the workflow is great now. It will run at midnight IST/5:30 AM UTC on the 15th of every month. I haven't tested this, but if it fails, I'll resolve it.

**Comment by not-nef** [comment]
> @not-nef why do you hate Futura-Tech? Close to your title, except I changed software to tech. Also, what do you guys think of a game in the future? Kind of like Atari Breakout?

I dont like tech. And the game idea is cool

**Comment by not-nef** [comment]
I held a presentation about the creator of Breakout, Steve Wozniak, yesterday

**Comment by not-nef** [comment]
@sumeshir26 What about futura-py?

**Comment by im-coder-lg** [comment]
Hmm, that seems cool. Also, Steve Jobs and Woz made the game. Woz did the schematics and boarding since you had to do those at that time and Jobs submitted the game to Nolan Bushnell. I know that due to the biography, read that a lot of times. Actually, I understand how Breakout works. You must start with a Ping Pong-like UI and add blocks. Then you must configure the blocks so that they disappear when the ball hits tgem. Slowly, the speed increases and etc. I thought of making this in JavaScript, React especially, but I think we could use PyGame to make the game.

**Comment by im-coder-lg** [comment]
> I held a presentation about the creator of Breakout, Steve Wozniak, yesterday

Wow. Actually, I played Breakout on Elgoog.com, it is easy to understand. Moreover, it doesn't need documentation. Okay, maybe a little, but I'll manage it.

**Comment by sumeshir26** [comment]
Okay, and i think push jobs are better than crontabs since we only need to format when a commit is pushed, right? Why unnecessarily waste GH's runners?

**Comment by im-coder-lg** [comment]
I said cronjob since you format once in a while, thereby using less runners. Moreover, instead of formatting immediately, if we wait, we could format more lines of code if we wait. Maybe I'll also try integrating a push notification workflow inside it to tell us the code is formatted.

**Comment by im-coder-lg** [comment]
Also, you don't need to waste runners. It will just trigger the runner which will start the work.

**Comment by im-coder-lg** [comment]
I'll have to change some links again.

**Review by sumeshir26 — APPROVED** [review]

**Comment by im-coder-lg** [comment]
Wait, hold up! We can't push the changes here. I'll do some tricks around and push it by Monday.

**Comment by im-coder-lg** [comment]
I'm almost done, just need to push the changes! Works on https://github.com/im-coder-lg/Calculator-made-with-Python!

**Comment by im-coder-lg** [comment]
Final test!

**Comment by im-coder-lg** [comment]
This works now!

**Review by im-coder-lg — APPROVED** [review]
Works! Tested on https://github.com/im-coder-lg/TimerX

**Comment by im-coder-lg** [comment]
If you are confused how it works, I am making a mind map so it's gonna be easy for you to understand.

**Review by sumeshir26 — APPROVED** [review]

**Comment by im-coder-lg** [comment]
Merging!

**Pull request merged**
