### PR TITLE
fix(bug97): modify setAlwaysOnTop() to somehow allow theme switches

### LINKED ISSUE #97: setAlwaysOnTop() error on switching themes
**Describe the bug**
In Line 460:
https://github.com/Futura-Py/TimerX/blob/d18616cb5a15a20a5b3f51e50a33e33cae64a9a7/main.py#L460

It takes only one positional arg but two(`app`) were given. Luckily, I know a fix.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Terminal
2. Run TimerX via Python
3. Experience error 
**Expected behaviour**
Supposed to launch with no errors.

**Screenshots**
hyuxn6K03d

**Desktop (please complete the following information):**

- OS: Raspbian Bullseye ARM64
- Version: Source Code

**Additional context**
I can fix this.

### PR DESCRIPTION
**Pull request by im-coder-lg**
How is it connected?
Anyway, closes #97

### CODE REVIEW

**Comment by im-coder-lg** [comment]
I'll add styling here?

**Review by sumeshir26 — APPROVED** [review]

**Comment by sumeshir26** [comment]
Nice idea!

**Comment by im-coder-lg** [comment]
And also, believe it or not, this was done on my Raspberry Pi and MobaXTerm, so I can't really guarantee if it works on Windows.

**Comment by im-coder-lg** [comment]
I'll test, hold up!

**Comment by im-coder-lg** [comment]
approved for me!

**Comment by im-coder-lg** [comment]
Also, formatted files, so plus point?

**Comment by im-coder-lg** [comment]
Also, I have a Twitter too, so I could promote TimerX. Hopefully, someone might look at this. Wy not enable the blog part on Docusaurus so that we could post changelogs and some more things to users?

**Comment by im-coder-lg** [comment]
If you allow me to post on Twitter, I can post only during the evening, school.

**Comment by sumeshir26** [comment]
its fine if you promote the app on twitter

**Comment by im-coder-lg** [comment]
Hmm, then it will be posted during the evening since I'll be back from school by then. What do you think of a Slack or Discord community? I think it's cool here.

**Review by not-nef — APPROVED** [review]

**Comment by not-nef** [comment]
> Hmm, then it will be posted during the evening since I'll be back from school by then. What do you think of a Slack or Discord community? I think it's cool here.

Discord sounds good i think, but i dont have it. Still think it would be the best option.

**Comment by not-nef** [comment]
I will return to discord … someday … pls dont ask about it ok?

**Comment by im-coder-lg** [comment]
Then I'll definitely ask about it. Human psychology?

**Comment by not-nef** [comment]
My parents dont like it when i talk to random ppl on the internet and thats why i dont have discord. They also dont know that i talk to you guys.

**Comment by not-nef** [comment]
I will return to discord someday, when they cant tell me what to do anymore. In 5 years.

**Comment by sumeshir26** [comment]
oh... ok np

**Comment by im-coder-lg** [comment]
Even my parents don't know I talk to you all 😜 guess we are on the same coin.

**Comment by not-nef** [comment]
Well, but my parents locked down my internet on my pc (and disabled the browser on my phone) and they monitor my phone. So i cant go on discord. Your parents atöeast don't monitor your pc and disable your internet. You can do what you want. I cant. :(

**Comment by im-coder-lg** [comment]
Hope you break that barrier one day tho...

**Comment by sumeshir26** [comment]
Well, my parents don’t know that I talk to you guys as well, so…

**Comment by sumeshir26** [comment]
If you don’t have internet how do you access GitHub?

**Comment by not-nef** [comment]
> If you don’t have internet how do you access GitHub?

Downloading Chrome on my phone for every commit.

**Comment by not-nef** [comment]
And for talking i use github mobile

**Comment by not-nef** [comment]
> Hope you break that barrier one day tho...

Me too :(

**Comment by sumeshir26** [comment]
anyway, when r you starting work on calcx? After 1.1 there isnt much we can do for tiimerx

**Comment by sumeshir26** [comment]
how does adding packages on Pypi wotk because i want to make a module which automaticallay makes the windw svttk And adds mica and forces dark titlebar and binds unmaximize to redraw titlebar

**Comment by not-nef** [comment]
> how does adding packages on Pypi wotk because i want to make a module which automaticallay makes the windw svttk And adds mica and forces dark titlebar and binds unmaximize to redraw titlebar

If you want, you can add it to ntkutils! It already has dark titlebar forcing and all the packaging is done! (And it needs more features lol) If you dont, i can set it up for you, just give me your source code!

**Comment by not-nef** [comment]
Great!

**Pull request merged**
