### PR TITLE
feat(docs): Restyle!

### PR DESCRIPTION
**Pull request by im-coder-lg**
Material UI for the documentation? It'd look good with icons. :thinking:

### CODE REVIEW

**Comment by im-coder-lg** [comment]
Oh yeah it's the fork, so had to rebase 44 commits. We'll just squash and merge.

**Comment by im-coder-lg** [comment]
Oh yeah it's the fork, so had to rebase 44 commits. We'll just squash and merge.

**Comment by im-coder-lg** [comment]
Also - anyone interested in Netlify CMS? That is just an admin panel, so if it is on our docs, we could make editing the content easier.

**Comment by im-coder-lg** [comment]
Also - anyone interested in Netlify CMS? That is just an admin panel, so if it is on our docs, we could make editing the content easier.

**Comment by sumeshir26** [comment]
I reallay dont like this at all. But can we keep the deafault docosauraus theme but add the sick gradient background?

**Comment by im-coder-lg** [comment]
Expected that. Have you checked mui.com for the components which you like? I mean there is a lot of it, so if you want, choose some components you want and put it here. I too hate the MUI buttons, but the contact us at component seems good as a pop-up. I'll try adding the gradient, time to get inspired by xplorer.space since they use Docusaurus. Also, what do you think of switching the docs base to Typescript? I kinda like it

**Comment by im-coder-lg** [comment]
Btw since March is exam month for 13-year olds, did you pass this academic year? I did, glad about it, but did you guys get the LGTM of passing? Hope you guys got that!

**Comment by sumeshir26** [comment]
Do whatever you think is best, let me look at Mui.com

**Comment by sumeshir26** [comment]
1. What is the new workflow for?
2. I like the contact us popup and the icons
3. I think we should keep evrything as the default theme expect for the gradnt background

**Comment by sumeshir26** [comment]
4. can we use #eb400a as the primary color snd the banner base color?

**Comment by im-coder-lg** [comment]
> What is the new workflow for?

Which workflow? If it's the formatting thing, I rebased after 44 commits, hence it could have overlapped. I'll delete it now.

> I like the contact us popup and the icons

Will add discord and GitHub there 🤔 ok?

> can we use #eb400a as the primary color snd the banner base color?

I'll see about it, maybe if I choose different colors form the same color family, then #satisfied?

**Comment by sumeshir26** [comment]
Yeah the formatting thing
Ok
Yeah, ,but keep thrr samr family since that is the timerx color  in the llogi

**Comment by im-coder-lg** [comment]
I'll try tomorrow. Free to use my dev center at that time.

**Review by sumeshir26 — APPROVED** [review]
Just saw this was still open - Merging...

**Comment by im-coder-lg** [comment]
This was effing open? Dang, I forgot with all the flipping school work. I think there is more to add, but my exams are coming. We both will have our holidays on October if I am not wrong, so I will try checking to integrate gradients and change the icon package. Or maybe we shall move to Astro.build(spoiler, it's freaking fast). Your ideas bud?

**Comment by sumeshir26** [comment]
Well, ur the website boss

**Comment by im-coder-lg** [comment]
And _you_ are the boss here. So, your ideas? I promise even if it doesn't seem like a good addition, I will make it as my base and refine that idea.

**Comment by sumeshir26** [comment]
Yeah, the graident might look good. Is there anyway to use Microsoft's Fluent icons on the web?

**Comment by im-coder-lg** [comment]
Not any that I know, but we could try MUI. Microsoft Fluent icons are available via Figma and as SVGs, so I don't know.

**Comment by sumeshir26** [comment]
Yeah, you can go ahead with MUI

**Comment by im-coder-lg** [comment]
Launching Project Restyle from October 2! Hope to add some pretty ground-breaking features by the end of my holidays!PS: tell more ideas, I will note it. Let's make sure it is less right now, so that we can execute via parts. Capische?

**Comment by im-coder-lg** [comment]
I have asked the Docusaurus team how to add gradients - I searched everywhere for a guide but couldn't find it. Meanwhile, I have a big feature upgrade coming for all of us.

Trust me, it will make our workflow easier.

**Comment by sumeshir26** [comment]
Cool!

**Pull request merged**
