### PR TITLE
feat: Discord.GG!

### PR DESCRIPTION
**Pull request by im-coder-lg**
Howzzat?

### CODE REVIEW

**Review by not-nef — APPROVED** [review]

**Comment by sumeshir26** [comment]
what discord? do we have one?

**Comment by not-nef** [comment]
@sumeshir26 apparently its https://discord.gg/dd64cjC8

**Comment by im-coder-lg** [comment]
I just made one. I read an article on Forem about expanding a project and one of the steps was to build a community. With Slack/Discord.

**Comment by sumeshir26** [comment]
@im-coder-lg I joined it, can you make me owner?

**Review by sumeshir26 — APPROVED** [review]

**Comment by im-coder-lg** [comment]
Yeah I'll make you a mod(erator).

**Pull request merged**
