### PR TITLE
Rebase to fbfbc61

### LINKED ISSUE #101: Turd, I messsed up, dont commit anything until i say so since i accidently pushed to master instead of a branch. Reverting...

### PR DESCRIPTION
**Pull request by im-coder-lg**
Oh my freaking god @sumeshir26, use Linux and OhMyZSH from now!
Resolves #101 
@not-nef you can safely ignore this. @sumeshir26 from now, try these tools/OSes:
- Linux dev env
- Some random IDE like code-server since it's lightweight for the Linux machine
- ZSH for the shell with oh-my-zsh (first) and Powerlevel10k (next) installed.
- If you want, use the Raspberry Pi _desktop kit_ so that you could set it up on any 7-15" monitors or go headless - regardless, you could use it as a desktop for ease of coding and testing or headless with MobaXTerm.
- 
Also, be really careful with commits if you don't want any of the above - use something that checks your commits.

### CODE REVIEW

**Review by sumeshir26 — APPROVED** [review]

**Comment by im-coder-lg** [comment]
Yo you sure it doesn't have your test changes?

**Comment by sumeshir26** [comment]
it dosent have them, ready for merge!

**Comment by im-coder-lg** [comment]
Merging!

**Comment by sumeshir26** [comment]
Yeah, I noticed that as well

**Pull request merged**
