### PR TITLE
docs: Replace org name(yet again)

### PR DESCRIPTION
**Pull request by im-coder-lg**

### CODE REVIEW

**Comment by im-coder-lg** [comment]
How does "The Futura Team" sound for the MIT copyright licensing in the LICENSE file as well as the website homepage?

**Comment by sumeshir26** [comment]
Sure

**Review by sumeshir26 — APPROVED** [review]

**Review by not-nef — APPROVED** [review]
👍

**Comment by im-coder-lg** [comment]
Wait, last thing left to do and I'll merge this myself.

**Pull request merged**
