### PR TITLE
feat: Update System

### PR DESCRIPTION
**Pull request by sumeshir26**
_Also I added a way to update the config when new settings are added!_

### CODE REVIEW

**Review by not-nef — APPROVED** [review]
Epic

**Comment by sumeshir26** [comment]
Merging this because @im-coder-lg is unavalaible

**Comment by im-coder-lg** [comment]
Yeah just searching for something. I'll test right now.

**Review by im-coder-lg — APPROVED** [review]
Looks so freaking good to me! 👍🏻 to merge!

**Pull request merged**
