### PR TITLE
docs: macOS support with WineHQ

### PR DESCRIPTION
**Pull request by im-coder-lg**
Sorry for all the clutter, Gitpod does all this. I am forced to push to forks when I have admin rights over the entire org.

### CODE REVIEW

**Comment by sumeshir26** [comment]
What even changed in this pr?

**Comment by im-coder-lg** [comment]
#74. I wanted to edit over at this repo. Sometimes, I tend to be an idiot though. Same situation here, I merged to this branch from my fork. I'll have to stop repeating this. But, basically, it's simple. I started with a formatting commit, then made the MDX and formatted yet again in the end. I also added formatting to the package.json so you can run it with npm. I think that makes the workflow(not Actions) easier while developing. But apart from code formatting, MDX and the new `fmt` and `fmt-check` script, nothing is new.

**Comment by im-coder-lg** [comment]
I'm going offline for a couple of hours. Just a heads up.

**Comment by im-coder-lg** [comment]
Alright, I'm back. Is this perfect?

**Comment by im-coder-lg** [comment]
Can we try adding a package.json to the root for adding Prettier as well as Docusaurus scripts? I will do some magic and tests around and add the changes through GitHub's UI. Btw, has anyone gained interest in code coverage recently?

**Comment by im-coder-lg** [comment]
I think this might be easy to understand, since all I will do is link the docs scripts to the root and add Prettier. Maybe if it works, I'll link the Python part too. It would be easy for us to script all this for ease of access as well as others to develop too, since all they will have to do is use npm.

**Comment by sumeshir26** [comment]
OK, tell me when I should merge

**Comment by im-coder-lg** [comment]
Not yet. I haven't committed the work since I had to go to school. Kinda ghastly, but not as and as the bugs I experience with the package.json, it's kinda riddled with it. I'll make it stable soon.

**Comment by im-coder-lg** [comment]
I'm halfway around, will commit soon!

**Comment by im-coder-lg** [comment]
I'm halfway around, will commit soon!

**Review by sumeshir26 — APPROVED** [review]

**Comment by sumeshir26** [comment]
@not-nef Waiting on your review!

**Comment by sumeshir26** [comment]
@not-nef

**Review by not-nef — APPROVED** [review]
Sorry @sumeshir26 i somehow missed that

**Comment by im-coder-lg** [comment]
I'll merge!

**Pull request merged**
