### PR TITLE
1.1

### PR DESCRIPTION
**Pull request by sumeshir26**

### CODE REVIEW

**Comment by im-coder-lg** [comment]
I'll have to do some changes, is it fine if I upload here?

**Comment by sumeshir26** [comment]
Sure

**Review by not-nef — APPROVED** [review]
Lookin good. Lets get this out!!

**Comment by sumeshir26** [comment]
@im-coder-lg Can you approve?

**Comment by im-coder-lg** [comment]
I need to update the website bro, can you wait till 6pm? We both are from India so it's of course IST.

**Comment by sumeshir26** [comment]
sure

**Comment by im-coder-lg** [comment]
Made you and @not-nef mods! Just noticed, the man just joined lol.

**Comment by sumeshir26** [comment]
yeah, but he said he wont be onlinee

**Comment by not-nef** [comment]
yes

**Comment by im-coder-lg** [comment]
But he could check in at times, right? That could be potentially useful.

**Comment by im-coder-lg** [comment]
@sumeshir26 I don't think I can do it man, I have science expo tomorrow and I made my project(Python!!!) and I need to do the chartwork. Can't do it, but can you try enabling blogs and creating a blog for 1.1 with changelogs? Make it fun to read too.

**Comment by sumeshir26** [comment]
Well, do we really need to do that because I was planning to write a actual change log for 1.1s release?

**Comment by im-coder-lg** [comment]
More visitors?

**Comment by im-coder-lg** [comment]
More visitors?

**Comment by sumeshir26** [comment]
i reallay dont know how to do that, you can do it after you return since i am a complete noob at docosoraus

**Comment by sumeshir26** [comment]
also, ProtonAOSP has a screenshot on their reallay nice docosauraus website, can we add one too?

**Comment by im-coder-lg** [comment]
We use Docusaurus. If you are asking about their CSSing, we could do the same in the custom stylesheet.

**Comment by sumeshir26** [comment]
ProtonApsp also uses docosauraus, check out ther website

**Comment by im-coder-lg** [comment]
I saw it, I expect it's their custom CSS. I'll add it in a new PR, you can merge this. Also, share me the release notes on discord, I'll update it to something better. I'll be busy for the time being, cleaning my PC up from my science expo thingies.

**Comment by im-coder-lg** [comment]
Well, the ProtonAOSP website ain't open-source; they customized their CSS styles, but since it isn't open-sourced here, I can't get their styling. Gosh, I can't do it, I just followed tutorials till now. I'll try finding more on this after exams, so can't help right now :(

**Comment by sumeshir26** [comment]
np, good luck!

**Comment by im-coder-lg** [comment]
Thanks!

**Pull request merged**
