### PR TITLE
fix(PR94): Theme switch+blur exclusivity

### PR DESCRIPTION
**Pull request by im-coder-lg**
yay
Fixed successfully!
I got some more ideas... I will try implementing them by tomorrow, it's Saturday for me and @sumeshir26. btw is this fine if I open a PR like this? Kinda easy to just rebase and merge, right?
Moreover, it was developed on Raspbian. :crossed_fingers:

### CODE REVIEW

**Comment by im-coder-lg** [comment]
A small conversation in 9f42a17, I request y'all to visit it. Also, @rdbende can you check if this works on KDE Neon? Sorry for the ping btw.

**Review by not-nef — APPROVED** [review]
epic

**Comment by im-coder-lg** [comment]
bro not yet lmao

**Comment by im-coder-lg** [comment]
yall got an idea to add @rdbende's Sun Valley messageboxes to TimerX's main app file? I just added 100+ lines of code from `utils.py`, rewired everything and finally set this up... I have an idea, will tell later.

**Comment by not-nef** [comment]
And why did you even add dialogs.py!!? We have them in utils.py!!

**Review by not-nef — CHANGES_REQUESTED** [review]
pls change

**Comment by im-coder-lg** [comment]
Oops, fixing that! The dialogs module needed the file, so I added it. Idiotic me.

**Comment by im-coder-lg** [comment]
> And why did you even add dialogs.py!!? We have them in utils.py!!

They don't seem to link, so I added it.

**Comment by im-coder-lg** [comment]
Also, I think dialogs.py seems a better shot on making popups, that's why I added it. Initially, I tried the utils code but it throwed errors, that's why I added dialogs.py, to simply the process. I'll add it to setup.py if it's fine.

**Comment by im-coder-lg** [comment]
pure waste of progress :\

**Pull request closed without merging**
